version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
  web:
    build: .
    command: waitress-serve --host=0.0.0.0 --port=8080 bookstore.wsgi:application
    volumes:
      - C:/Users/dluzr/Desktop/daniloalr-repo/bookstore:/usr/src/app/
    ports:
      - 8080:8080
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=railway
      - SQL_USER=postgres
      - SQL_PASSWORD=UzxgyTCgqGHAtbmfwFvzGnNUpahgQkib
      - SQL_HOST=autorack.proxy.rlwy.net
      - SQL_PORT=14550
    env_file:
      - ./env.dev
    depends_on:
      - db

volumes:
  postgres_data:
  app_data:
